# 8 Deep Learning with Keras

## 8.1 Keras Basics

### Detect whether bank notes are forged

#### Preprocess data

In [1]:
import numpy as np
# read CSV tables
from numpy import genfromtxt

In [2]:
# 5 columns x 1372 rows (samples)
# column 0-3: input features, already extracted
# column 4: label = 0 forgery, 1 real
data = genfromtxt('../../data/bank_note_data.txt', delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
data.shape

(1372, 5)

In [5]:
labels = data[:,4]

In [6]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [7]:
features = data[:,:4]

In [8]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [9]:
X = features
y = labels

In [10]:
# We use Scikit-Learn for splitting the dataset
from sklearn.model_selection import train_test_split

In [12]:
# train_test_split Shift TAB, scroll down to example
# it is important to randomize
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [13]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [14]:
len(X_train)

919

In [15]:
len(X_test)

453

In [17]:
y_train.shape

(919,)

In [18]:
# Scale features
from sklearn.preprocessing import MinMaxScaler

In [19]:
X_test.max()

17.1116

In [20]:
X_test.min()

-13.2869

In [21]:
# We create a scaler object,
# fit the X_train to it (min-max range)
# and then transform it (scale to the range [0,1])
scaler_object = MinMaxScaler()

In [22]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [23]:
scaled_X_train = scaler_object.transform(X_train)

In [24]:
# IMPORTANT: we fit (select scaling min-max range) to the TRAIN split only,
# because otherwise we're extracting info from the test split
# if a test sample has the max (peak) value!
scaled_X_test = scaler_object.transform(X_test)

In [25]:
scaled_X_train.max()

1.0000000000000002

In [26]:
scaled_X_test.max()

1.02679563427227

In [27]:
scaled_X_train.min()

0.0

In [28]:
scaled_X_test.min()

-0.0010694864308909147

#### Create a neural network model & train it

In [29]:
from keras.models import Sequential
# We use fully-connected layers in this example
from keras.layers import Dense

Using TensorFlow backend.


In [30]:
# Create model, then add the layers
model = Sequential()

# Add input layer: neurons, input dimenstion, activation
# input dimension is necessary only for the input layer
model.add(Dense(4, input_dim=4, activation='relu'))

# Add hidden layer: neurons, activation function
# Often we use something between 1x - 2x the neurons in the input layer
model.add(Dense(8, activation='relu'))

# Add ouput layer
# The output layer should have the sigmoid activation to fit the result to [0,1]
model.add(Dense(1, activation='sigmoid'))

In [31]:
# We compile the model and define
# loss function, optimization strategy, the metric used
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [33]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 4)                 20        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 9         
Total params: 69
Trainable params: 69
Non-trainable params: 0
_________________________________________________________________


In [77]:
# Train the model: X & y are passed, and the number of epochs
# In an epoch, teh whole dataset is used for training once
# With verbose, the loss and accuracy are displayed for each epoch
model.fit(scaled_X_train, y_train, epochs=50, verbose=2)

Epoch 1/50
 - 1s - loss: 0.7442 - acc: 0.5495
Epoch 2/50
 - 0s - loss: 0.7063 - acc: 0.5495
Epoch 3/50
 - 0s - loss: 0.6835 - acc: 0.5495
Epoch 4/50
 - 0s - loss: 0.6623 - acc: 0.5506
Epoch 5/50
 - 0s - loss: 0.6453 - acc: 0.5713
Epoch 6/50
 - 0s - loss: 0.6332 - acc: 0.6115
Epoch 7/50
 - 0s - loss: 0.6221 - acc: 0.6464
Epoch 8/50
 - 0s - loss: 0.6117 - acc: 0.6670
Epoch 9/50
 - 0s - loss: 0.6023 - acc: 0.6703
Epoch 10/50
 - 0s - loss: 0.5923 - acc: 0.6910
Epoch 11/50
 - 0s - loss: 0.5823 - acc: 0.7062
Epoch 12/50
 - 0s - loss: 0.5719 - acc: 0.7291
Epoch 13/50
 - 0s - loss: 0.5619 - acc: 0.7432
Epoch 14/50
 - 0s - loss: 0.5508 - acc: 0.7508
Epoch 15/50
 - 0s - loss: 0.5399 - acc: 0.7573
Epoch 16/50
 - 0s - loss: 0.5295 - acc: 0.7661
Epoch 17/50
 - 0s - loss: 0.5180 - acc: 0.7900
Epoch 18/50
 - 0s - loss: 0.5077 - acc: 0.7769
Epoch 19/50
 - 0s - loss: 0.4975 - acc: 0.8172
Epoch 20/50
 - 0s - loss: 0.4872 - acc: 0.8063
Epoch 21/50
 - 0s - loss: 0.4762 - acc: 0.8270
Epoch 22/50
 - 0s - lo

#### Infer test split and compute metrics

In [58]:
y_pred = model.predict_classes(scaled_X_test)

In [70]:
y_pred[0:5]

array([[0],
       [1],
       [0],
       [0],
       [0]], dtype=int32)

In [60]:
model.metrics_names

['loss', 'acc']

In [78]:
# We display the confussion matrix with TP, TN, FP, FN
from sklearn.metrics import confusion_matrix, classification_report

In [79]:
confusion_matrix(y_test, y_pred)

array([[248,   9],
       [ 12, 184]])

In [80]:
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

        0.0       0.95      0.96      0.96       257
        1.0       0.95      0.94      0.95       196

avg / total       0.95      0.95      0.95       453



#### Save and load the model

In [64]:
model.save('my_super_model.h5')

In [65]:
from keras.models import load_model

In [66]:
newmodel = load_model('my_super_model.h5')

In [69]:
# We can infer as before
y_pred = newmodel.predict_classes(scaled_X_test)

In [71]:
y_pred[0:5]

array([[0],
       [1],
       [0],
       [0],
       [0]], dtype=int32)