# Numpy: Quick Start

## 1. Basics

### 1.1 Array Creation

In [3]:
import numpy as np

In [4]:
np.__version__

'1.23.5'

In [3]:
# Array creation: literals passed; always use [] or () and np.array()
a = np.array([[1., 0., 0.], [0., 1., 2.]])

In [4]:
a.ndim # number of axes/dismensions

2

In [5]:
a.shape # items per dimension

(2, 3)

In [6]:
a.size # number of elements

6

In [8]:
a.dtype

dtype('float64')

In [9]:
a.itemsize # Size in bytes of each element

8

In [15]:
a.data # buffer containing the actual elements of the array, not used

In [16]:
type(a) # numpy.ndarray

numpy.ndarray

In [17]:
# Array creation: arange + reshape
b = np.arange(15).reshape(3, 5)

In [18]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
# Array creation: pass type with dtype
# https://numpy.org/doc/stable/user/basics.types.html
# np.bool_, np.byte = np.int8, np.short = np.int16, 
# np.half = np.float16, np.int_ = np.int64, , np.uint = np.uint64, np.double = np.float64, etc.
c = np.array([[1, 2], [3, 4]], dtype=complex)

In [20]:
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [21]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [23]:
np.empty((2, 3)) # random initial content; default dtype=float64, but can be changed

array([[6.23042070e-307, 1.11263583e-320, 0.00000000e+000],
       [7.52160003e-312, 0.00000000e+000, 1.05699581e-307]])

In [40]:
np.random.random((2, 3)) # random

array([[0.02696024, 0.64153749, 0.22699875],
       [0.58508639, 0.36995817, 0.52910146]])

In [24]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [26]:
print(np.arange(24).reshape(2, 3, 4)) # Print: last axis left to right, second-to-last top to bottom, rest separated in frames

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### 1.2 Array Operations

In [28]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)

In [31]:
a - b

array([20, 29, 38, 47])

In [30]:
b**2

array([0, 1, 4, 9])

In [32]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [33]:
a < 35

array([ True,  True, False, False])

In [34]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

In [35]:
A * B # elementwise product

array([[2, 0],
       [0, 4]])

In [36]:
A @ B # matrix product

array([[5, 4],
       [3, 4]])

In [37]:
A.dot(B) # another matrix product

array([[5, 4],
       [3, 4]])

In [45]:
a = np.random.random((2, 3))

In [46]:
a

array([[0.04804052, 0.89780936, 0.45839968],
       [0.17575413, 0.09403629, 0.58864803]])

In [42]:
a.sum() # we can specify axis, else overall; axis=0 -> sum in columns, axis=1 -> rows

2.3818352769755435

In [43]:
a.min() # we can specify axis, else overall; axis=0 -> in columns, axis=1 -> rows

0.11855861196103401

In [44]:
a.cumsum() # we can specify axis; axis=0 -> in columns, axis=1 -> rows

array([0.11855861, 0.29622298, 0.74542818, 0.96332904, 1.89178724,
       2.38183528])

### 1.3 Universal Functions

Universal functions, `ufunc`, are optimized vectorized functions that operate element-wise on NumPy arrays, producing an array as output.

#### Mathematical Operations
1. **Addition, Subtraction, Multiplication, Division**: `np.add`, `np.subtract`, `np.multiply`, `np.divide`
2. **Square, Square Root, Power**: `np.square`, `np.sqrt`, `np.power`
3. **Exponential and Logarithmic**: `np.exp`, `np.log`, `np.log10`, `np.log2`

#### Trigonometric Functions
1. **Sine, Cosine, Tangent**: `np.sin`, `np.cos`, `np.tan`
2. **Inverse Trigonometric Functions**: `np.arcsin`, `np.arccos`, `np.arctan`

#### Hyperbolic Functions
1. **Sinh, Cosh, Tanh**: `np.sinh`, `np.cosh`, `np.tanh`
2. **Inverse Hyperbolic Functions**: `np.arcsinh`, `np.arccosh`, `np.arctanh`

#### Bitwise Operations
1. **AND, OR, XOR, NOT**: `np.bitwise_and`, `np.bitwise_or`, `np.bitwise_xor`, `np.bitwise_not`

#### Comparison Functions
1. **Greater, Less, Equal**: `np.greater`, `np.less`, `np.equal`
2. **Logical Operations**: `np.logical_and`, `np.logical_or`, `np.logical_not`

#### Floating Functions
1. **Is finite, Is infinite, Is NaN**: `np.isfinite`, `np.isinf`, `np.isnan`
2. **Floor, Ceil, Round**: `np.floor`, `np.ceil`, `np.round`

#### Statistics and Aggregates
1. **Sum, Product, Cumulative Sum**: `np.sum`, `np.prod`, `np.cumsum`
2. **Minimum, Maximum**: `np.min`, `np.max`

In [56]:
# We can also create ufuncs based on a python function using numpy.frompyfunc
# https://numpy.org/doc/stable/reference/generated/numpy.frompyfunc.html#numpy.frompyfunc
a = np.arange(1,10,2)

In [55]:
def add_two(a):
    return a + 2

In [57]:
ufunc_add_two = np.frompyfunc(add_two, 1, 1)

In [58]:
ufunc_add_two(np.array((10, 30, 100)))

array([12, 32, 102], dtype=object)

### 1.4 Indexing, Slicing and Iterating

In [59]:
a = np.arange(10)**3

In [60]:
a[2]

8

In [61]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [62]:
a[:6:2] = 1000

In [63]:
a[::-1]  # reversed a

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [71]:
b = np.arange(0,200,5).reshape(5,8)

In [73]:
b

array([[  0,   5,  10,  15,  20,  25,  30,  35],
       [ 40,  45,  50,  55,  60,  65,  70,  75],
       [ 80,  85,  90,  95, 100, 105, 110, 115],
       [120, 125, 130, 135, 140, 145, 150, 155],
       [160, 165, 170, 175, 180, 185, 190, 195]])

In [75]:
b[2, 1:3] # dimensions separated by commas, ndarrays returned

array([85, 90])

In [77]:
b[-1] # last row

array([160, 165, 170, 175, 180, 185, 190, 195])

## 2. Shape Manipulation

### 2.1 Changing the Shape

Important functions:

- `reshape()`: change shape, original data in memory not modified; C-style is followed if not stated otherwise (`a[0, 0], a[0, 1], ...`), which does not change the underlying data order in memory.
- `ravel()`: flatten `ndarray`, orginal data in memory not modified; C-style is followed if not stated otherwise (`a[0, 0], a[0, 1], ...`), which does not change the underlying data order in memory.
- `resize()`: it returns a new array in memory with the specified size/shape, we might have more or less items than the original; if more, old values are repeated. Note that the original variable is changed without re-assigning it, i.e., it changes the `self`.

In [21]:
a = np.floor(10 * np.random.random((3, 4)))

In [22]:
a

array([[4., 5., 6., 9.],
       [4., 4., 6., 3.],
       [4., 6., 0., 7.]])

In [23]:
a.shape

(3, 4)

In [24]:
a.ravel()  # returns the array, flattened

array([4., 5., 6., 9., 4., 4., 6., 3., 4., 6., 0., 7.])

In [25]:
a.reshape(6, 2)  # returns the array with a modified shape

array([[4., 5.],
       [6., 9.],
       [4., 4.],
       [6., 3.],
       [4., 6.],
       [0., 7.]])

In [27]:
a.T  # returns the array, transposed

array([[4., 4., 4.],
       [5., 4., 6.],
       [6., 6., 0.],
       [9., 3., 7.]])

In [28]:
a

array([[4., 5., 6., 9.],
       [4., 4., 6., 3.],
       [4., 6., 0., 7.]])

In [29]:
a.resize((2, 6))

In [30]:
a

array([[4., 5., 6., 9., 4., 4.],
       [6., 3., 4., 6., 0., 7.]])

In [31]:
a.reshape(3, -1) # If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated

array([[4., 5., 6., 9.],
       [4., 4., 6., 3.],
       [4., 6., 0., 7.]])

### 2.2 Stacking and splitting arrays

In [32]:
a = np.floor(10 * np.random.random((2, 2)))

In [33]:
a

array([[0., 2.],
       [2., 6.]])

In [34]:
b = np.floor(10 * np.random.random((2, 2)))

In [35]:
b

array([[3., 9.],
       [8., 3.]])

In [36]:
np.vstack((a, b))

array([[0., 2.],
       [2., 6.],
       [3., 9.],
       [8., 3.]])

In [37]:
np.hstack((a, b))

array([[0., 2., 3., 9.],
       [2., 6., 8., 3.]])

In [40]:
a = np.floor(10 * np.random.random((2, 12)))

In [41]:
a

array([[8., 1., 4., 8., 4., 7., 4., 4., 6., 8., 6., 6.],
       [7., 9., 8., 5., 9., 1., 0., 2., 8., 4., 0., 4.]])

In [39]:
# Split `a` into 3
# See also vsplit for vertical splits
np.hsplit(a, 3)

[array([[4., 1., 5., 3.],
        [6., 0., 6., 3.]]),
 array([[7., 5., 9., 7.],
        [5., 3., 0., 3.]]),
 array([[4., 4., 3., 8.],
        [2., 5., 9., 1.]])]

In [42]:
# Split `a` after the third and the fourth column
# See also vsplit for vertical splits
np.hsplit(a, (3, 4))

[array([[8., 1., 4.],
        [7., 9., 8.]]),
 array([[8.],
        [5.]]),
 array([[4., 7., 4., 4., 6., 8., 6., 6.],
        [9., 1., 0., 2., 8., 4., 0., 4.]])]

## 3. Copies and Views

When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. There are three cases:

- No Copy at All
- View or Shallow Copy
- Deep Copy

### 3.1 No Copy at All

- Assignments make no copies!
- Passing an array (mutable) to a function is done by reference, i.e., no copies!

In [43]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

In [44]:
# Simple assignments make no copy of objects or their data
b = a   # no new object is created
b is a  # a and b are two names for the same ndarray object

True

In [48]:
# Python passes mutable objects as references, so function calls make no copy
def f(x):
    print(id(x))

In [46]:
id(a)  # id is a unique identifier of an object 

1526839275024

In [47]:
f(a)

1526839275024


### 3.2 View or Shallow Copy

Different array objects can share the same data, i.e., the memory buffer containing the data is the same for all of them. The `view()` method creates a new array object that looks at the same data; other methods do the same, such as:

- Slicing an array returns a view of it!
- `reshape()`
- `ravel()`
- In some cases, `hsplit()` and `vsplit()`

However, these operations **do not return a view, but create a new array in memory**:

- `resize()`
- `hstack()`, `vstack()`

In [49]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

In [50]:
c = a.view()

In [51]:
c is a

False

In [52]:
c.base is a  # c is a view of the data owned by a

True

In [53]:
c.flags.owndata

False

In [54]:
c = c.reshape((2, 6)) # a's shape doesn't change

In [55]:
a.shape

(3, 4)

In [57]:
c[0, 4] = 1234 # a's data changes

In [58]:
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [59]:
s = a[:, 1:3]

In [60]:
s[:] = 10  # s[:] is a view of s. Note the difference between s = 10 and s[:] = 10

In [61]:
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

### 3.3 Deep Copy

The `copy()` method makes a complete copy of the array and its data.
Sometimes `copy()` should be called after slicing if the original array is not required anymore

In [62]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])

In [63]:
d = a.copy()  # a new array object with new data is created

In [64]:
d is a

False

In [65]:
d.base is a  # d doesn't share anything with a

False

In [66]:
d[0, 0] = 9999

In [67]:
d

array([[9999,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11]])

In [68]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
# We should copy() slices of huge arrays to avoid copying many data
a = np.arange(int(1e8))
b = a[:100].copy()
del a  # the memory of ``a`` can be released.

## 4. Functions and Methods Overview

See [Functions and Methods Overview](https://numpy.org/doc/stable/user/quickstart.html#functions-and-methods-overview).

## 5. Advanced indexing and index tricks